title: Julio Espinoza # your name (or website title) here
logo: "images/photo_self.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data, Data, Data
  <br><br>
  When I'm not looking at data, you can find me hiking, learning more about personal finance, hiking, or finding a great food spot.
  <br><br>
  <a href="https://www.linkedin.com/in/jbespinoza/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
